# Generated by Django 5.2 on 2025-04-28 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100)),
                ('major', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
            ],
        ),
    ]
