# Generated by Django 5.2 on 2025-04-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mentor'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
