# Generated by Django 5.2.1 on 2025-05-15 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
